### ISSUE TITLE
I am unable to see any messages, only dice works

### ISSUE THREAD

**Issue by researchase** [Awesomium-Team/Telegram-message-UE#1]
I am using ue 5.03 on mac m1, the only thing that works is the dice so I feel the token and user id is correct. ( I used the demo) but nothing else works, please can you let me know if I am missing something?

**Comment by MrKuBu** [comment]
Hi, I guess the problem is now API telegram or internet connection. Try to send a message a little later, if everything is the same, then I will collect a debug version for you to track the work telegram.

**Comment by MrKuBu** [comment]
I understand that the problem is solved?
